export const REGISTER_BASIC_DOCTOR_REQUEST = "REGISTER_BASIC_DOCTOR_REQUEST"
export const REGISTER_BASIC_DOCTOR_SUCCESS = "REGISTER_BASIC_DOCTOR_SUCCESS"
export const REGISTER_BASIC_DOCTOR_FAIL = "REGISTER_BASIC_DOCTOR_FAIL"

export const REGISTER_EDUC_DOCTOR_REQUEST = "REGISTER_EDUC_DOCTOR_REQUEST"
export const REGISTER_EDUC_DOCTOR_SUCCESS = "REGISTER_EDUC_DOCTOR_SUCCESS"
export const REGISTER_EDUC_DOCTOR_FAIL = "REGISTER_EDUC_DOCTOR_FAIL"

export const REGISTER_SPECIALTY_DOCTOR_REQUEST = "REGISTER_SPECIALTY_DOCTOR_REQUEST"
export const REGISTER_SPECIALTY_DOCTOR_SUCCESS = "REGISTER_SPECIALTY_DOCTOR_SUCCESS"
export const REGISTER_SPECIALTY_DOCTOR_FAIL = "REGISTER_SPECIALTY_DOCTOR_FAIL"

export const GET_DOCTOR_TITLE_BASIC_REQUEST ='GET_DOCTOR_TITLE_BASIC_REQUEST'
export const GET_DOCTOR_TITLE_BASIC_FAIL = "GET_DOCTOR_TITLE_BASIC_FAIL"
export const GET_DOCTOR_TITLE_BASIC_SUCCESS = "GET_DOCTOR_TITLE_BASIC_SUCCESS"