export const USER_SIGNIN_REQUEST="USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT= "USER_SIGN_OUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const GETALLDOCTOR_REQUEST = "GETALLDOCTOR_REQUEST";
export const GETALLDOCTOR_SUCCESS = "GETALLDOCTOR_SUCCESS";
export const GETALLDOCTOR_FAIL = "GETALLDOCTOR_FAIL";

export const SAVE_APPOINTMENT_REQUEST_1 = "SAVE_APPOINTMENT_REQUEST_1";
export const REMOVE_APPOINTMENT_REQUEST = "REMOVE_APPOINTMENT_REQUEST";
export const ADD_MEDICAL_CARD = "ADD_MEDICAL_CARD";
export const REMOVE_MEDICAL_CARD = "REMOVE_MEDICAL_CARD";
export const ADD_DENTIST_INFO = "ADD_DENTIST_INFO";


export const GET_APPOINTMENT_REQUEST = "GET_APPOINTMENT_REQUEST"
export const GET_APPOINTMENT_SUCCESS = "GET_APPOINTMENT_SUCCESS"
export const GET_APPOINTMENT_FAIL = "GET_APPOINTMENT_FAIL"

export const CHECK_EMAIL_REQUEST = "CHECK_EMAIL_REQUEST"
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS"
export const CHECK_EMAIL_FAIL = "CHECK_EMAIL_FAIL"


export const SAVE_PATIENT_DET = "SAVE_PATIENT_DET"
export const SAVE_PATIENT_SUC = "SAVE_PATIENT_SUC"
export const SAVE_PATIENT_FAIL = "SAVE_PATIENT_FAIL"

export const SAVE_APPOINTMENT_REQUEST = "SAVE_APPOINTMENT_REQUEST";
export const SAVE_APPOINTMENT_FAIL = "SAVE_APPOINTMENT_FAIL";
export const SAVE_APPOINTMENT_SUCCESS = "SAVE_APPOINTMENT_SUCCESS";

export const DELETE_APPOINTMENT_REQUEST = "DELETE_APPOINTMENT_REQUEST"
export const DELETE_APPOINTMENT_SUCCESS = "DELETE_APPOINTMENT_SUCCESS"
export const DELETE_APPOINTMENT_FAIL = "DELETE_APPOINTMENT_FAIL"

export const GET_USER_DETAIL_REQ = "GET_USER_DETAIL_REQ"
export const GET_USER_DETAIL_FAIL = "GET_USER_DETAIL_FAIL"
export const GET_USER_DETAIL_SUC = "GET_USER_DETAIL_SUC"

export const UPDATE_USER_DETAIL_REQ = "UPDATE_USER_DETAIL_REQ"
export const UPDATE_USER_DETAIL_FAIL = "UPDATE_USER_DETAIL_FAIL"
export const UPDATE_USER_DETAIL_SUC = "UPDATE_USER_DETAIL_SUC"
